import 'dotenv/config';
import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path';
import express from 'express'; import helmet from 'helmet'; import morgan from 'morgan'; import multer from 'multer'; import jwt from 'jsonwebtoken';
import swaggerUi from 'swagger-ui-express';
import { openDatabase } from './db.js'; import { compareVersions } from './version.js';
import { buildUpdatePackageFromZip, getReleasePolicy, inspectPackageZip, normalizeFutureDeadline } from './release.js';
import { openApiDocument } from './openapi.js';
import { CHANNELS, canAccess, ensureInitialAdmin, hashPassword, userScopes, verifyPassword } from './auth.js';
import { registerPortalRoutes } from './portal.js';
const app=express(), port=Number(process.env.PORT||3333);
const db=openDatabase(path.resolve(process.env.DATABASE_PATH||'./data/updater.db'));
ensureInitialAdmin(db,process.env.ADMIN_USER,process.env.ADMIN_PASSWORD);
const packagesPath=path.resolve(process.env.PACKAGES_PATH||'./packages'), downloadBase=String(process.env.DOWNLOAD_BASE_URL||'').replace(/\/$/,'');
const storagePath=path.resolve(process.env.CLIENT_STORAGE_PATH||'./storage');
const incomingPath=path.join(packagesPath,'.incoming');
fs.mkdirSync(packagesPath,{recursive:true}); fs.mkdirSync(path.join(packagesPath,'.temp'),{recursive:true}); fs.mkdirSync(incomingPath,{recursive:true});
const upload=multer({dest:path.join(packagesPath,'.temp'),limits:{fileSize:1024*1024*1024}});
app.set('trust proxy',Number(process.env.TRUST_PROXY||1)); app.use(helmet()); app.use(express.json({limit:process.env.ERROR_JSON_LIMIT||'12mb'})); app.use(morgan('combined'));
// No desenvolvimento o Next encaminha /downloads para esta rota. Em producao,
// o Nginx pode continuar servindo a mesma pasta diretamente.
app.use('/downloads',express.static(packagesPath,{fallthrough:false,index:false}));
app.get('/api-docs.json',(_q,res)=>res.json(openApiDocument));
app.use('/docs',swaggerUi.serve,swaggerUi.setup(openApiDocument,{customSiteTitle:'Central de Atualização API'}));
const adminAuth=(req,res,next)=>{try{const token=jwt.verify((req.get('authorization')||'').replace(/^Bearer /,''),process.env.JWT_SECRET);const user=db.prepare('SELECT id,username,name,role,active FROM app_user WHERE id=?').get(token.sub);if(!user?.active)throw new Error();req.user=user;req.scopes=userScopes(db,user);next();}catch{res.status(401).json({error:'unauthorized'});}};
const installationAuth=(req,res,next)=>{const value=(req.get('authorization')||'').replace(/^Bearer /,'');if(!process.env.INSTALLATION_KEY||value!==process.env.INSTALLATION_KEY)return res.status(401).json({error:'invalid_installation_key'});next();};
const ciAuth=(req,res,next)=>{const value=(req.get('authorization')||'').replace(/^Bearer /,'');try{const hash=crypto.createHash('sha256').update(value).digest('hex'),user=db.prepare('SELECT id,username,name,role,active FROM app_user WHERE api_token_hash=?').get(hash),productIds=db.prepare('SELECT product_id FROM api_token_product WHERE user_id=?').all(user?.id).map(item=>item.product_id),channels=db.prepare('SELECT channel FROM api_token_channel WHERE user_id=?').all(user?.id).map(item=>item.channel);if(!value||!user?.active||!productIds.length||!channels.length)throw new Error();req.user=user;req.scopes={all:false,productIds,channels};next();}catch{res.status(401).json({error:'invalid_api_token'});}};
const hashFile=file=>new Promise((resolve,reject)=>{const h=crypto.createHash('sha256');fs.createReadStream(file).on('error',reject).on('data',d=>h.update(d)).on('end',()=>resolve(h.digest('hex')));});
const hashFileSync=file=>{const hash=crypto.createHash('sha256'),buffer=Buffer.allocUnsafe(1024*1024),handle=fs.openSync(file,'r');try{let bytes;do{bytes=fs.readSync(handle,buffer,0,buffer.length,null);if(bytes)hash.update(buffer.subarray(0,bytes));}while(bytes);return hash.digest('hex');}finally{fs.closeSync(handle);}};
const textValue=value=>value===undefined||value===null||String(value).trim()===''?null:String(value).trim();
function errorSignature(exceptionClass,message){return crypto.createHash('sha256').update(`${String(exceptionClass||'').trim().toLowerCase()}\n${String(message||'').replace(/\s+/g,' ').trim().toLowerCase()}`).digest('hex');}
function errorFixStatus(fix,version){if(!fix)return null;const current=textValue(version),valid=current&&current!=='-';const comparison=valid?compareVersions(current,fix.version):null;return{...fix,status:comparison===null?'unknown':comparison<0?'update_required':'already_fixed',currentVersion:valid?current:null};}
function knownFixFor(signature,productCode,channel,version){const fix=db.prepare(`SELECT k.id,k.note,k.created_at,k.updated_at,r.id releaseId,r.version,r.channel,r.artifact_type artifactType,r.active,r.blocked,p.code productCode,p.name productName FROM known_error_fix k JOIN release r ON r.id=k.release_id JOIN product p ON p.id=k.product_id WHERE k.signature=? AND p.code=? AND k.channel=?`).get(signature,productCode,channel);return errorFixStatus(fix,version);}
function normalizeErrorDate(value){if(!value)return new Date().toISOString();const br=String(value).match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2}):(\d{2})$/);const date=br?new Date(`${br[3]}-${br[2]}-${br[1]}T${br[4]}:${br[5]}:${br[6]}`):new Date(value);if(Number.isNaN(date.getTime()))throw new Error('invalid_error_date');return date.toISOString();}
function normalizeScreenshot(value){if(!value)return null;const match=String(value).match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/s),mime=match?.[1]||'image/png',base64=(match?.[2]||String(value)).replace(/\s/g,'');if(!/^[A-Za-z0-9+/]*={0,2}$/.test(base64))throw new Error('invalid_screenshot_base64');const bytes=Buffer.from(base64,'base64');if(!bytes.length||bytes.length>8*1024*1024)throw new Error('invalid_screenshot_size');return{base64,mime};}
const cryptoInfo=Buffer.from('central-atualizacao:error-payload:v1');
function cryptoPart(value,name,expected){const text=String(value||'').replace(/\s/g,'');if(!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw new Error(`invalid_${name}`);const result=Buffer.from(text,'base64');if(!result.length||(expected&&result.length!==expected))throw new Error(`invalid_${name}`);return result;}
function normalizeKeyTerminalId(terminalId){return String(terminalId||'').trim().toLowerCase();}
function errorKey(terminalId,salt){const ikm=Buffer.from(`${normalizeKeyTerminalId(terminalId)}:${process.env.INSTALLATION_KEY||''}`,'utf8');try{return Buffer.from(crypto.hkdfSync('sha256',ikm,salt,cryptoInfo,32));}finally{ikm.fill(0);}}
function decryptEnvelope(terminalId,envelope){const salt=cryptoPart(envelope.salt,'salt'),iv=cryptoPart(envelope.iv,'iv',12),tag=cryptoPart(envelope.authTag,'auth_tag',16),ciphertext=cryptoPart(envelope.ciphertext,'ciphertext'),key=errorKey(terminalId,salt);try{const decipher=crypto.createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);return{plain:Buffer.concat([decipher.update(ciphertext),decipher.final()]),salt,iv,tag,ciphertext,key};}catch{throw new Error('error_payload_authentication_failed');}}
function encryptErrorPayload(terminalId,payload){const salt=crypto.randomBytes(32),iv=crypto.randomBytes(12),key=errorKey(terminalId,salt),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),plain=Buffer.from(JSON.stringify(payload),'utf8'),ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag(),result={salt:salt.toString('base64'),iv:iv.toString('base64'),authTag:tag.toString('base64'),ciphertext:ciphertext.toString('base64')};plain.fill(0);key.fill(0);return result;}
function decryptStoredError(error){const decrypted=decryptEnvelope(error.key_terminal_id,{salt:error.crypto_salt,iv:error.crypto_iv,authTag:error.crypto_auth_tag,ciphertext:error.encrypted_payload});try{return{payload:JSON.parse(decrypted.plain.toString('utf8')),plain:decrypted.plain,key:decrypted.key};}catch{decrypted.plain.fill(0);decrypted.key.fill(0);throw new Error('invalid_encrypted_error_payload');}}
function registerInstallation(body){const{client,terminal,product='pdv',channel='production',currentVersion='0.0.0'}=body;if(!client?.id||!client?.name||!terminal?.id||!terminal?.name)throw new Error('invalid_installation');
 db.prepare(`INSERT INTO client(external_id,name,document) VALUES(?,?,?) ON CONFLICT(external_id) DO UPDATE SET name=excluded.name,document=excluded.document,last_seen_at=CURRENT_TIMESTAMP`).run(client.id,client.name,client.document||null);
 const c=db.prepare('SELECT id FROM client WHERE external_id=?').get(client.id);
 db.prepare(`INSERT INTO terminal(external_id,client_id,name,computer_name,product_code,channel,current_version,os_version) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(external_id) DO UPDATE SET client_id=excluded.client_id,name=excluded.name,computer_name=excluded.computer_name,product_code=excluded.product_code,channel=excluded.channel,current_version=excluded.current_version,os_version=excluded.os_version,last_seen_at=CURRENT_TIMESTAMP`).run(terminal.id,c.id,terminal.name,terminal.computerName||null,product,channel,currentVersion,terminal.osVersion||null);
 return{client:c,terminal:db.prepare('SELECT * FROM terminal WHERE external_id=?').get(terminal.id)};}
app.get('/health',(_q,r)=>r.json({ok:true}));
app.post('/api/v1/auth/login',(req,res)=>{const user=db.prepare('SELECT * FROM app_user WHERE username=?').get(String(req.body?.user||'').trim());if(!user?.active||!verifyPassword(req.body?.password,user.password_hash))return res.status(401).json({error:'invalid_credentials'});res.json({token:jwt.sign({sub:user.id},process.env.JWT_SECRET,{expiresIn:'8h'}),user:{id:user.id,username:user.username,name:user.name,role:user.role}});});
app.get('/api/v1/admin/me',adminAuth,(req,res)=>res.json({...req.user,scopes:req.scopes}));
app.get('/api/v1/admin/me/api-token',adminAuth,(req,res)=>res.json({productIds:db.prepare('SELECT product_id FROM api_token_product WHERE user_id=?').all(req.user.id).map(item=>item.product_id),channels:db.prepare('SELECT channel FROM api_token_channel WHERE user_id=?').all(req.user.id).map(item=>item.channel),createdAt:db.prepare('SELECT api_token_created_at FROM app_user WHERE id=?').get(req.user.id).api_token_created_at}));
app.post('/api/v1/admin/me/api-token',adminAuth,(req,res)=>{const productIds=[...new Set((req.body.productIds||[]).map(Number))],channels=[...new Set(req.body.channels||[])];if(!productIds.length||!channels.length)return res.status(400).json({error:'scope_required'});if(channels.some(channel=>!CHANNELS.includes(channel)))return res.status(400).json({error:'invalid_channel'});const allowed=allowedProducts(req).map(product=>product.id);if(!req.scopes.all&&productIds.some(id=>!allowed.includes(id)))return res.status(403).json({error:'scope_denied'});const token=`ci_${crypto.randomBytes(32).toString('base64url')}`,hash=crypto.createHash('sha256').update(token).digest('hex');db.transaction(()=>{db.prepare('UPDATE app_user SET api_token_hash=?,api_token_created_at=CURRENT_TIMESTAMP WHERE id=?').run(hash,req.user.id);db.prepare('DELETE FROM api_token_product WHERE user_id=?').run(req.user.id);db.prepare('DELETE FROM api_token_channel WHERE user_id=?').run(req.user.id);for(const productId of productIds)db.prepare('INSERT INTO api_token_product(user_id,product_id) VALUES(?,?)').run(req.user.id,productId);for(const channel of channels)db.prepare('INSERT INTO api_token_channel(user_id,channel) VALUES(?,?)').run(req.user.id,channel);})();res.status(201).json({token,productIds,channels});});
app.delete('/api/v1/admin/me/api-token',adminAuth,(req,res)=>{db.transaction(()=>{db.prepare('UPDATE app_user SET api_token_hash=NULL,api_token_created_at=NULL WHERE id=?').run(req.user.id);db.prepare('DELETE FROM api_token_product WHERE user_id=?').run(req.user.id);db.prepare('DELETE FROM api_token_channel WHERE user_id=?').run(req.user.id);})();res.json({revoked:true});});
app.post('/api/v1/ci/artifacts',ciAuth,upload.single('artifact'),(req,res,next)=>{const file=req.file;try{if(!file||path.extname(file.originalname).toLowerCase()!=='.zip')throw new Error('zip_required');const productCode=textValue(req.body.product)||'pdv',version=textValue(req.body.version),channel=textValue(req.body.channel);if(!version)throw new Error('version_required');if(!CHANNELS.includes(channel))throw new Error('invalid_channel');const product=db.prepare('SELECT id FROM product WHERE code=? AND active=1').get(productCode);if(!product)throw new Error('product_not_found');if(!canAccess(req.scopes,product.id,channel)){if(file?.path&&fs.existsSync(file.path))fs.unlinkSync(file.path);return res.status(403).json({error:'scope_denied'});}const id=crypto.randomUUID(),relativePath=`.incoming/${id}.zip`,storedPath=path.join(packagesPath,relativePath);fs.renameSync(file.path,storedPath);const sha256=hashFileSync(storedPath),sizeBytes=fs.statSync(storedPath).size;db.prepare('INSERT INTO ci_artifact(id,user_id,product_code,version,channel,file_path,original_name,sha256,size_bytes) VALUES(?,?,?,?,?,?,?,?,?)').run(id,req.user.id,productCode,version,channel,relativePath,file.originalname,sha256,sizeBytes);res.status(201).json({id,product:productCode,version,channel,fileName:file.originalname,sha256,sizeBytes,status:'pending'});}catch(e){if(file?.path&&fs.existsSync(file.path))fs.unlinkSync(file.path);next(e);}});
app.post('/api/v1/updates/check',installationAuth,(req,res)=>{try{const reg=registerInstallation(req.body),{product='pdv',channel='production',currentVersion='0.0.0'}=req.body;
 const releases=db.prepare(`SELECT DISTINCT r.* FROM release r JOIN product p ON p.id=r.product_id JOIN release_target rt ON rt.release_id=r.id WHERE p.code=? AND r.channel=? AND r.active=1 AND r.blocked=0 AND (rt.target_type='all' OR (rt.target_type='client' AND rt.client_id=?)) ORDER BY r.published_at DESC,r.id DESC`).all(product,channel,reg.client.id);
 const release=releases.find(r=>compareVersions(r.version,currentVersion)>0),policy=getReleasePolicy(release),status=release?'update_available':'no_update',message=release?`Versão ${release.version} disponível (${release.artifact_type})${policy.deadlineExpired?' e obrigatória por prazo vencido':''}.`:'Terminal já está atualizado.';
 db.prepare('INSERT INTO terminal_event(terminal_id,release_id,previous_version,target_version,status,message,ip) VALUES(?,?,?,?,?,?,?)').run(reg.terminal.id,release?.id||null,currentVersion,release?.version||null,status,message,req.ip);
 if(!release)return res.json({available:false,currentVersion});res.json({available:true,releaseId:String(release.id),version:release.version,mandatory:policy.mandatory,mandatoryReason:policy.mandatoryReason,deadlineAt:release.deadline_at,deadlineExpired:policy.deadlineExpired,minimumVersion:release.minimum_version,artifactType:release.artifact_type||'package',fileName:release.original_name||path.basename(release.file_path),downloadUrl:`${downloadBase}/${release.file_path}`,sha256:release.sha256,sizeBytes:release.size_bytes,notes:release.show_notes_pdv?release.technical_notes:null,showNotesPdv:Boolean(release.show_notes_pdv)});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/v1/updates/events',installationAuth,(req,res)=>{const t=db.prepare('SELECT id FROM terminal WHERE external_id=?').get(req.body.terminalId);if(!t)return res.status(404).json({error:'terminal_not_found'});const release=req.body.targetVersion?db.prepare(`SELECT r.id FROM release r JOIN product p ON p.id=r.product_id WHERE r.version=? AND p.code=? ORDER BY r.id DESC LIMIT 1`).get(req.body.targetVersion,req.body.product||'pdv'):null;db.prepare('INSERT INTO terminal_event(terminal_id,release_id,previous_version,target_version,status,message,ip) VALUES(?,?,?,?,?,?,?)').run(t.id,release?.id||null,req.body.previousVersion||null,req.body.targetVersion||null,req.body.status,req.body.message||null,req.ip);res.status(202).json({accepted:true});});
app.post('/api/v1/errors',installationAuth,(req,res)=>{let decrypted;try{const body=req.body||{},terminalId=normalizeKeyTerminalId(body.terminalId);if(!terminalId)throw new Error('terminal_id_required');decrypted=decryptEnvelope(terminalId,body);const diagnostic=JSON.parse(decrypted.plain.toString('utf8')),exceptionClass=textValue(diagnostic.exceptionClass||diagnostic.exception),message=textValue(diagnostic.message);if(!exceptionClass)throw new Error('exception_required');if(!message)throw new Error('message_required');const terminal=db.prepare('SELECT id,product_code FROM terminal WHERE lower(trim(external_id))=?').get(terminalId),product=terminal?.product_code||textValue(body.product)||'pdv',setting=db.prepare('SELECT store_screenshot FROM error_setting WHERE id=1').get(),rawScreenshot=diagnostic.screenshotBase64??diagnostic.base64??diagnostic.print,screenshot=setting?.store_screenshot?normalizeScreenshot(rawScreenshot):null;if(screenshot)diagnostic.screenshotBase64=`data:${screenshot.mime};base64,${screenshot.base64}`;else delete diagnostic.screenshotBase64;delete diagnostic.base64;delete diagnostic.print;const encrypted=encryptErrorPayload(terminalId,diagnostic),result=db.prepare('INSERT INTO application_error(terminal_id,product_code,occurred_at,exception_class,message,screenshot_mime,ip,key_terminal_id,crypto_salt,crypto_iv,crypto_auth_tag,encrypted_payload) VALUES(?,?,CURRENT_TIMESTAMP,?,?,?,?,?,?,?,?,?)').run(terminal?.id||null,product,'<encrypted>','<encrypted>',screenshot?.mime||null,req.ip,terminalId,encrypted.salt,encrypted.iv,encrypted.authTag,encrypted.ciphertext);res.status(201).json({accepted:true,id:Number(result.lastInsertRowid),screenshotStored:Boolean(screenshot)});}catch(e){res.status(400).json({error:e.message});}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);decrypted.ciphertext.fill(0);}}});
const allowedProducts=req=>req.scopes.all?db.prepare('SELECT * FROM product ORDER BY name').all():db.prepare('SELECT p.* FROM product p JOIN user_product up ON up.product_id=p.id WHERE up.user_id=? ORDER BY p.name').all(req.user.id);
const allowedProductCodes=req=>allowedProducts(req).map(p=>p.code);
function notifyReleasePublished(releaseId,product,channel,version){
 const admins=db.prepare(`SELECT id FROM app_user WHERE active=1 AND role='admin'`).all();
 const title=`Nova versão ${version}`;
 const message=`${product.name} publicou a versão ${version} no canal ${channel}.`;
 const insert=db.prepare('INSERT INTO admin_notification(user_id,type,title,message,release_id) VALUES(?,?,?,?,?)');
 for(const admin of admins){
  const scopes=userScopes(db,admin);
  if(canAccess(scopes,product.id,channel))insert.run(admin.id,'release_published',title,message,releaseId);
 }
}
app.get('/api/v1/admin/dashboard',adminAuth,(req,res)=>{const requested=[...new Set(String(req.query.channel||CHANNELS.join(',')).split(',').filter(channel=>CHANNELS.includes(channel)))],selected=req.scopes.all?requested:requested.filter(channel=>req.scopes.channels.includes(channel)),codes=allowedProductCodes(req);if(!selected.length)return res.json({channels:[],clients:0,terminals:0,releases:0,errors:0});const channelMarks=selected.map(()=>'?').join(','),productWhere=req.scopes.all?'':`AND product_code IN (${codes.map(()=>'?').join(',')||'NULL'})`,clients=db.prepare(`SELECT count(DISTINCT client_id) value FROM terminal WHERE channel IN (${channelMarks}) ${productWhere}`).get(...selected,...(req.scopes.all?[]:codes)).value,terminals=db.prepare(`SELECT count(*) value FROM terminal WHERE channel IN (${channelMarks}) ${productWhere}`).get(...selected,...(req.scopes.all?[]:codes)).value,releases=req.scopes.all?db.prepare(`SELECT count(*) value FROM release WHERE active=1 AND channel IN (${channelMarks})`).get(...selected).value:db.prepare(`SELECT count(*) value FROM release WHERE active=1 AND channel IN (${channelMarks}) AND product_id IN (${req.scopes.productIds.map(()=>'?').join(',')||'NULL'})`).get(...selected,...req.scopes.productIds).value,errors=req.scopes.all?db.prepare(`SELECT count(*) value FROM application_error e JOIN terminal t ON t.id=e.terminal_id WHERE e.received_at>=datetime('now','-7 days') AND t.channel IN (${channelMarks})`).get(...selected).value:db.prepare(`SELECT count(*) value FROM application_error e JOIN terminal t ON t.id=e.terminal_id WHERE e.received_at>=datetime('now','-7 days') AND t.channel IN (${channelMarks}) AND e.product_code IN (${codes.map(()=>'?').join(',')||'NULL'})`).get(...selected,...codes).value;res.json({channels:selected,clients,terminals,releases,errors});});
app.get('/api/v1/admin/notifications',adminAuth,(req,res)=>{const items=db.prepare(`SELECT n.*,r.version,p.name product_name,r.channel FROM admin_notification n LEFT JOIN release r ON r.id=n.release_id LEFT JOIN product p ON p.id=r.product_id WHERE n.user_id=? ORDER BY n.created_at DESC,n.id DESC LIMIT 50`).all(req.user.id);const unread=db.prepare('SELECT count(*) value FROM admin_notification WHERE user_id=? AND read_at IS NULL').get(req.user.id).value;res.json({items,unread});});
app.post('/api/v1/admin/notifications/read',adminAuth,(req,res)=>{db.prepare('UPDATE admin_notification SET read_at=CURRENT_TIMESTAMP WHERE user_id=? AND read_at IS NULL').run(req.user.id);res.json({updated:true});});
app.get('/api/v1/admin/clients',adminAuth,(req,res)=>{const codes=allowedProductCodes(req),scoped=!req.scopes.all;if(scoped&&(!codes.length||!req.scopes.channels.length))return res.json([]);const where=scoped?`WHERE t.product_code IN (${codes.map(()=>'?').join(',')}) AND t.channel IN (${req.scopes.channels.map(()=>'?').join(',')})`:'';res.json(db.prepare(`SELECT c.*,count(t.id) terminal_count,max(t.last_seen_at) last_terminal_seen FROM client c JOIN terminal t ON t.client_id=c.id ${where} GROUP BY c.id ORDER BY c.last_seen_at DESC`).all(...(scoped?[...codes,...req.scopes.channels]:[])));});
app.get('/api/v1/admin/clients/:id/terminals',adminAuth,(req,res)=>{const codes=allowedProductCodes(req);res.json(req.scopes.all?db.prepare('SELECT * FROM terminal WHERE client_id=? ORDER BY last_seen_at DESC').all(req.params.id):codes.length&&req.scopes.channels.length?db.prepare(`SELECT * FROM terminal WHERE client_id=? AND product_code IN (${codes.map(()=>'?').join(',')}) AND channel IN (${req.scopes.channels.map(()=>'?').join(',')}) ORDER BY last_seen_at DESC`).all(req.params.id,...codes,...req.scopes.channels):[]);});
app.get('/api/v1/admin/terminals/:id/logs',adminAuth,(req,res)=>{const terminal=db.prepare('SELECT * FROM terminal WHERE id=?').get(req.params.id);if(!terminal)return res.status(404).json({error:'terminal_not_found'});const product=db.prepare('SELECT id FROM product WHERE code=?').get(terminal.product_code);if(!req.scopes.all&&(!product||!req.scopes.productIds.includes(product.id)||!req.scopes.channels.includes(terminal.channel)))return res.status(403).json({error:'scope_denied'});res.json(db.prepare(`SELECT e.id,e.status,e.message,e.previous_version,e.target_version,e.ip,e.created_at FROM terminal_event e WHERE e.terminal_id=? ORDER BY e.created_at DESC,e.id DESC`).all(terminal.id));});
app.get('/api/v1/admin/products',adminAuth,(req,res)=>res.json(allowedProducts(req)));
app.get('/api/v1/admin/artifacts',adminAuth,(req,res)=>{const rows=db.prepare('SELECT a.*,p.name product_name FROM ci_artifact a LEFT JOIN product p ON p.code=a.product_code WHERE a.user_id=? AND a.consumed_at IS NULL ORDER BY a.created_at DESC').all(req.user.id);res.json(rows.map(item=>{try{const file=path.resolve(packagesPath,item.file_path);return{...item,file_count:file.startsWith(incomingPath+path.sep)&&fs.existsSync(file)?inspectPackageZip(file).files.length:null};}catch{return{...item,file_count:null};}}));});
app.get('/api/v1/admin/artifacts/:id/manifest',adminAuth,(req,res,next)=>{try{const artifact=db.prepare('SELECT a.*,p.id product_id,p.name product_name FROM ci_artifact a LEFT JOIN product p ON p.code=a.product_code WHERE a.id=? AND a.user_id=? AND a.consumed_at IS NULL').get(req.params.id,req.user.id);if(!artifact)return res.status(404).json({error:'artifact_not_found'});if(!canAccess(req.scopes,artifact.product_id,artifact.channel))return res.status(403).json({error:'scope_denied'});const file=path.resolve(packagesPath,artifact.file_path);if(!file.startsWith(incomingPath+path.sep)||!fs.existsSync(file))throw new Error('artifact_file_not_found');res.json({artifact,inspection:inspectPackageZip(file)});}catch(e){next(e);}});
app.delete('/api/v1/admin/artifacts/:id',adminAuth,(req,res,next)=>{try{const artifact=db.prepare('SELECT a.*,p.id product_id FROM ci_artifact a LEFT JOIN product p ON p.code=a.product_code WHERE a.id=? AND a.user_id=? AND a.consumed_at IS NULL').get(req.params.id,req.user.id);if(!artifact)return res.status(404).json({error:'artifact_not_found'});if(!canAccess(req.scopes,artifact.product_id,artifact.channel))return res.status(403).json({error:'scope_denied'});db.prepare('DELETE FROM ci_artifact WHERE id=? AND consumed_at IS NULL').run(artifact.id);const file=path.resolve(packagesPath,artifact.file_path);if(file.startsWith(incomingPath+path.sep)&&fs.existsSync(file))fs.unlinkSync(file);res.json({deleted:true});}catch(e){next(e);}});
app.post('/api/v1/admin/products',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const r=db.prepare('INSERT INTO product(code,name) VALUES(?,?)').run(req.body.code,req.body.name);res.status(201).json({id:r.lastInsertRowid});});
app.delete('/api/v1/admin/products/:id',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const product=db.prepare('SELECT * FROM product WHERE id=?').get(req.params.id);if(!product)return res.status(404).json({error:'product_not_found'});if(db.prepare('SELECT 1 FROM release WHERE product_id=? LIMIT 1').get(product.id)||db.prepare('SELECT 1 FROM terminal WHERE product_code=? LIMIT 1').get(product.code))return res.status(409).json({error:'product_in_use'});db.prepare('DELETE FROM product WHERE id=?').run(product.id);res.json({deleted:true});});
app.get('/api/v1/admin/products/:id/delete-impact',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const product=db.prepare('SELECT * FROM product WHERE id=?').get(req.params.id);if(!product)return res.status(404).json({error:'product_not_found'});res.json({canDelete:!db.prepare('SELECT 1 FROM release WHERE product_id=? LIMIT 1').get(product.id)&&!db.prepare('SELECT 1 FROM terminal WHERE product_code=? LIMIT 1').get(product.code),releases:db.prepare('SELECT count(*) value FROM release WHERE product_id=?').get(product.id).value,terminals:db.prepare('SELECT count(*) value FROM terminal WHERE product_code=?').get(product.code).value});});
app.get('/api/v1/admin/releases',adminAuth,(req,res)=>{const {productId,channel}=req.query;let where=[] ,args=[];if(!req.scopes.all){where.push(`r.product_id IN (${req.scopes.productIds.map(()=>'?').join(',')||'NULL'})`,`r.channel IN (${req.scopes.channels.map(()=>'?').join(',')||'NULL'})`);args.push(...req.scopes.productIds,...req.scopes.channels);}if(productId){where.push('r.product_id=?');args.push(productId);}if(channel){where.push('r.channel=?');args.push(channel);}res.json(db.prepare(`SELECT r.*,p.name product_name,group_concat(CASE WHEN rt.target_type='all' THEN 'Todos' ELSE c.name END,', ') targets,(SELECT count(*) FROM terminal t WHERE t.product_code=p.code AND t.channel=r.channel AND t.current_version=r.version) terminal_count FROM release r JOIN product p ON p.id=r.product_id JOIN release_target rt ON rt.release_id=r.id LEFT JOIN client c ON c.id=rt.client_id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY r.id ORDER BY r.published_at DESC`).all(...args));});
app.get('/api/v1/admin/releases/:id/details',adminAuth,(req,res)=>{const release=db.prepare(`SELECT r.*,p.name product_name,p.code product_code,u.name published_by_name,group_concat(CASE WHEN rt.target_type='all' THEN 'Todos os clientes' ELSE c.name END,', ') targets FROM release r JOIN product p ON p.id=r.product_id JOIN release_target rt ON rt.release_id=r.id LEFT JOIN client c ON c.id=rt.client_id LEFT JOIN app_user u ON u.id=r.published_by WHERE r.id=? GROUP BY r.id`).get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const successful="'installed','updated','success'",installations=db.prepare(`SELECT date(e.created_at,'localtime') day,c.id client_id,c.name client_name,t.id terminal_id,t.name terminal_name,t.computer_name,e.created_at FROM terminal_event e JOIN terminal t ON t.id=e.terminal_id JOIN client c ON c.id=t.client_id WHERE e.release_id=? AND e.status IN (${successful}) ORDER BY e.created_at DESC`).all(release.id),days=db.prepare(`SELECT date(e.created_at,'localtime') day,count(DISTINCT t.client_id) client_count,count(DISTINCT e.terminal_id) terminal_count FROM terminal_event e JOIN terminal t ON t.id=e.terminal_id WHERE e.release_id=? AND e.status IN (${successful}) GROUP BY date(e.created_at,'localtime') ORDER BY day DESC`).all(release.id);res.json({...release,days,installations});});
app.get('/api/v1/admin/releases/:id/manifest',adminAuth,(req,res,next)=>{try{const release=db.prepare(`SELECT r.*,p.name product_name,p.code product_code FROM release r JOIN product p ON p.id=r.product_id WHERE r.id=?`).get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});if(release.artifact_type==='sql')return res.json({release,inspection:{hasManifest:false,files:[{destination:release.original_name||path.basename(release.file_path),sizeBytes:release.size_bytes,sha256:release.sha256,source:release.original_name||path.basename(release.file_path)}]}});const file=path.resolve(packagesPath,release.file_path);if(!file.startsWith(packagesPath+path.sep)||!fs.existsSync(file))throw new Error('release_file_not_found');res.json({release,inspection:inspectPackageZip(file)});}catch(e){next(e);}});
app.get('/api/v1/admin/logs',adminAuth,(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit)||100,1),500),ids=req.scopes.productIds;res.json(db.prepare(`SELECT e.id,e.status,e.message,e.previous_version,e.target_version,e.ip,e.created_at,t.name terminal_name,t.computer_name,c.name client_name,r.artifact_type,p.name product_name FROM terminal_event e LEFT JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id LEFT JOIN release r ON r.id=e.release_id LEFT JOIN product p ON p.id=r.product_id ${req.scopes.all?'':`WHERE (r.product_id IN (${ids.map(()=>'?').join(',')||'NULL'}) OR t.product_code IN (SELECT code FROM product WHERE id IN (${ids.map(()=>'?').join(',')||'NULL'})))`} ORDER BY e.created_at DESC,e.id DESC LIMIT ?`).all(...(req.scopes.all?[]:[...ids,...ids]),limit));});
app.get('/api/v1/admin/errors/settings',adminAuth,(_req,res)=>{const setting=db.prepare('SELECT store_screenshot FROM error_setting WHERE id=1').get();res.json({storeScreenshot:Boolean(setting?.store_screenshot)});});
app.patch('/api/v1/admin/errors/settings',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});db.prepare('UPDATE error_setting SET store_screenshot=? WHERE id=1').run(req.body.storeScreenshot?1:0);res.json({updated:true,storeScreenshot:Boolean(req.body.storeScreenshot)});});
app.get('/api/v1/admin/terminals/:id/errors/analysis',adminAuth,(req,res)=>{try{
 const terminal=db.prepare('SELECT * FROM terminal WHERE id=?').get(req.params.id);if(!terminal)return res.status(404).json({error:'terminal_not_found'});const productAccess=db.prepare('SELECT id FROM product WHERE code=?').get(terminal.product_code);if(!req.scopes.all&&(!productAccess||!req.scopes.productIds.includes(productAccess.id)||!req.scopes.channels.includes(terminal.channel)))return res.status(403).json({error:'scope_denied'});
 const today=new Date(),defaultStart=new Date(today.getTime()-29*86400000),parseDay=(value,fallback)=>{const date=value?new Date(`${value}T00:00:00`):fallback;if(Number.isNaN(date.getTime()))throw new Error('invalid_error_period');return date;},start=parseDay(req.query.startDate,defaultStart),end=parseDay(req.query.endDate,today),days=Math.floor((end-start)/86400000)+1;if(days<1||days>90)throw new Error('error_period_must_be_between_1_and_90_days');const endExclusive=new Date(end.getTime()+86400000);
 const rows=db.prepare(`SELECT e.*,c.name client_name,t.name registered_terminal_name,t.channel,p.name product_name FROM application_error e JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id LEFT JOIN product p ON p.code=e.product_code WHERE e.terminal_id=? AND e.received_at>=? AND e.received_at<? AND e.encrypted_payload IS NOT NULL ORDER BY e.received_at DESC,e.id DESC`).all(terminal.id,start.toISOString(),endExclusive.toISOString()),valid=[];let invalidCount=0;
 for(const row of rows){let decrypted;try{decrypted=decryptStoredError(row);const payload=decrypted.payload,exceptionClass=textValue(payload.exceptionClass||payload.exception),message=textValue(payload.message);if(!exceptionClass||!message){invalidCount++;continue;}const version=textValue(payload.version)||'-',client=row.client_name||'Não identificado',product=row.product_name||row.product_code,channel=row.channel||'Não identificado',terminalName=textValue(payload.terminal)||row.registered_terminal_name||'-',signature=errorSignature(exceptionClass,message),knownFix=knownFixFor(signature,row.product_code,channel,version);valid.push({id:row.id,receivedAt:row.received_at,date:payload.date||payload.data||null,exception:exceptionClass,message,version,client,product,productCode:row.product_code,channel,terminal:terminalName,hasScreenshot:Boolean(row.screenshot_mime),signature,knownFix});}catch{invalidCount++;}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}}
 const unique=values=>[...new Set(values)].sort((a,b)=>a.localeCompare(b,'pt-BR')),options={exceptions:unique(valid.map(x=>x.exception)),clients:unique(valid.map(x=>x.client)),versions:unique(valid.map(x=>x.version)),products:unique(valid.map(x=>x.product)),channels:unique(valid.map(x=>x.channel))},selected={exception:req.query.exception,client:req.query.client,version:req.query.version,product:req.query.product,channel:req.query.channel},filtered=valid.filter(x=>(!selected.exception||x.exception===selected.exception)&&(!selected.client||x.client===selected.client)&&(!selected.version||x.version===selected.version)&&(!selected.product||x.product===selected.product)&&(!selected.channel||x.channel===selected.channel)),groups=new Map;
 for(const item of filtered){const key=[item.signature,item.client,item.version,item.product,item.channel].join('|'),current=groups.get(key);if(current){current.occurrences++;if(item.receivedAt>current.receivedAt){current.id=item.id;current.receivedAt=item.receivedAt;current.date=item.date;current.hasScreenshot=item.hasScreenshot;}}else groups.set(key,{...item,occurrences:1});}
 const items=[...groups.values()].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt)),chart=(field)=>{const map=new Map;for(const item of filtered){const signatures=map.get(item[field])||new Set;signatures.add(item.signature);map.set(item[field],signatures);}return[...map].map(([label,signatures])=>({label,count:signatures.size})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'pt-BR'));};res.json({items,options,charts:{byException:chart('exception'),byClient:chart('client')},uniqueCount:new Set(filtered.map(x=>x.signature)).size,occurrenceCount:filtered.length,invalidCount,terminal:{id:terminal.id,name:terminal.name},period:{startDate:req.query.startDate||start.toISOString().slice(0,10),endDate:req.query.endDate||end.toISOString().slice(0,10),maxDays:90}});
 }catch(e){res.status(400).json({error:e.message});}});
app.get('/api/v1/admin/errors/analysis',adminAuth,(req,res)=>{try{
 const today=new Date(),defaultStart=new Date(today.getTime()-29*86400000),parseDay=(value,fallback)=>{const date=value?new Date(`${value}T00:00:00`):fallback;if(Number.isNaN(date.getTime()))throw new Error('invalid_error_period');return date;},start=parseDay(req.query.startDate,defaultStart),end=parseDay(req.query.endDate,today),days=Math.floor((end-start)/86400000)+1;if(days<1||days>90)throw new Error('error_period_must_be_between_1_and_90_days');const endExclusive=new Date(end.getTime()+86400000),codes=allowedProductCodes(req),scoped=!req.scopes.all;
 if(scoped&&(!codes.length||!req.scopes.channels.length))return res.json({items:[],options:{exceptions:[],clients:[],versions:[],products:[],channels:[]},charts:{byException:[],byClient:[]},uniqueCount:0,occurrenceCount:0,invalidCount:0});
 const scope=scoped?`AND e.product_code IN (${codes.map(()=>'?').join(',')}) AND t.channel IN (${req.scopes.channels.map(()=>'?').join(',')})`:'',rows=db.prepare(`SELECT e.*,c.name client_name,t.name registered_terminal_name,t.channel,p.name product_name FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id LEFT JOIN product p ON p.code=e.product_code WHERE e.received_at>=? AND e.received_at<? AND e.encrypted_payload IS NOT NULL ${scope} ORDER BY e.received_at DESC,e.id DESC`).all(start.toISOString(),endExclusive.toISOString(),...(scoped?[...codes,...req.scopes.channels]:[])),valid=[];let invalidCount=0;
 for(const row of rows){let decrypted;try{decrypted=decryptStoredError(row);const payload=decrypted.payload,exceptionClass=textValue(payload.exceptionClass||payload.exception),message=textValue(payload.message);if(!exceptionClass||!message){invalidCount++;continue;}const version=textValue(payload.version)||'-',client=row.client_name||'Não identificado',product=row.product_name||row.product_code,channel=row.channel||'Não identificado',terminal=textValue(payload.terminal)||row.registered_terminal_name||'-',signature=errorSignature(exceptionClass,message),knownFix=knownFixFor(signature,row.product_code,channel,version);valid.push({id:row.id,receivedAt:row.received_at,date:payload.date||payload.data||null,exception:exceptionClass,message,version,client,product,productCode:row.product_code,channel,terminal,hasScreenshot:Boolean(row.screenshot_mime),signature,knownFix});}catch{invalidCount++;}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}}
 const unique=values=>[...new Set(values)].sort((a,b)=>a.localeCompare(b,'pt-BR')),options={exceptions:unique(valid.map(x=>x.exception)),clients:unique(valid.map(x=>x.client)),versions:unique(valid.map(x=>x.version)),products:unique(valid.map(x=>x.product)),channels:unique(valid.map(x=>x.channel))},selected={exception:req.query.exception,client:req.query.client,version:req.query.version,product:req.query.product,channel:req.query.channel},filtered=valid.filter(x=>(!selected.exception||x.exception===selected.exception)&&(!selected.client||x.client===selected.client)&&(!selected.version||x.version===selected.version)&&(!selected.product||x.product===selected.product)&&(!selected.channel||x.channel===selected.channel)),groups=new Map;
 for(const item of filtered){const key=[item.signature,item.client,item.version,item.product,item.channel].join('|'),current=groups.get(key);if(current){current.occurrences++;if(item.receivedAt>current.receivedAt){current.id=item.id;current.receivedAt=item.receivedAt;current.date=item.date;current.hasScreenshot=item.hasScreenshot;}}else groups.set(key,{...item,occurrences:1});}
 const items=[...groups.values()].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt)),chart=(field)=>{const map=new Map;for(const item of filtered){const signatures=map.get(item[field])||new Set;signatures.add(item.signature);map.set(item[field],signatures);}return[...map].map(([label,signatures])=>({label,count:signatures.size})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'pt-BR'));};res.json({items,options,charts:{byException:chart('exception'),byClient:chart('client')},uniqueCount:new Set(filtered.map(x=>x.signature)).size,occurrenceCount:filtered.length,invalidCount,period:{startDate:req.query.startDate||start.toISOString().slice(0,10),endDate:req.query.endDate||end.toISOString().slice(0,10),maxDays:90}});
 }catch(e){res.status(400).json({error:e.message});}});
app.get('/api/v1/admin/errors',adminAuth,(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit)||200,1),500),codes=allowedProductCodes(req),scoped=!req.scopes.all;if(scoped&&(!codes.length||!req.scopes.channels.length))return res.json([]);const where=scoped?`WHERE e.product_code IN (${codes.map(()=>'?').join(',')}) AND t.channel IN (${req.scopes.channels.map(()=>'?').join(',')})`:'';res.json(db.prepare(`SELECT e.id,e.product_code,e.received_at,e.screenshot_mime IS NOT NULL has_screenshot,c.name client_name,t.name registered_terminal_name FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id ${where} ORDER BY e.received_at DESC,e.id DESC LIMIT ?`).all(...(scoped?[...codes,...req.scopes.channels]:[]),limit));});
app.use('/api/v1/admin/errors/:id',adminAuth,(req,res,next)=>{if(req.scopes.all)return next();const error=db.prepare(`SELECT p.id product_id,t.channel FROM application_error e LEFT JOIN product p ON p.code=e.product_code LEFT JOIN terminal t ON t.id=e.terminal_id WHERE e.id=?`).get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});if(!req.scopes.productIds.includes(error.product_id)||!req.scopes.channels.includes(error.channel))return res.status(403).json({error:'scope_denied'});next();});
app.get('/api/v1/admin/errors/:id',adminAuth,(req,res)=>{const error=db.prepare(`SELECT e.*,c.name client_name,t.external_id terminal_external_id,t.channel FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id WHERE e.id=?`).get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});const product=db.prepare('SELECT id FROM product WHERE code=?').get(error.product_code);if(!req.scopes.all&&(!product||!req.scopes.productIds.includes(product.id)))return res.status(403).json({error:'scope_denied'});let decrypted;try{decrypted=decryptStoredError(error);const payload={...decrypted.payload};delete payload.screenshotBase64;delete payload.base64;delete payload.print;const exceptionClass=textValue(payload.exceptionClass||payload.exception),message=textValue(payload.message),version=textValue(payload.version)||'-',signature=errorSignature(exceptionClass,message),knownFix=knownFixFor(signature,error.product_code,error.channel,version);res.set('Cache-Control','no-store, private').json({id:error.id,product_code:error.product_code,channel:error.channel,received_at:error.received_at,client_name:error.client_name,terminal_external_id:error.terminal_external_id,hasScreenshot:Boolean(error.screenshot_mime),signature,knownFix,...payload});}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}});
app.get('/api/v1/admin/errors/:id/fix-options',adminAuth,(req,res)=>{const error=db.prepare(`SELECT e.product_code,t.channel FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id WHERE e.id=?`).get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});const product=db.prepare('SELECT * FROM product WHERE code=?').get(error.product_code);if(!product)return res.status(404).json({error:'product_not_found'});if(!canAccess(req.scopes,product.id,error.channel))return res.status(403).json({error:'scope_denied'});res.json(db.prepare(`SELECT r.id,r.version,r.channel,r.artifact_type,r.active,r.blocked,r.published_at FROM release r WHERE r.product_id=? AND r.channel=? ORDER BY r.published_at DESC,r.id DESC`).all(product.id,error.channel));});
app.put('/api/v1/admin/errors/:id/known-fix',adminAuth,(req,res)=>{const error=db.prepare(`SELECT e.*,t.channel FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id WHERE e.id=?`).get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});const release=db.prepare(`SELECT r.*,p.code product_code FROM release r JOIN product p ON p.id=r.product_id WHERE r.id=?`).get(req.body.releaseId);if(!release)return res.status(404).json({error:'release_not_found'});if(release.product_code!==error.product_code||release.channel!==error.channel)return res.status(400).json({error:'release_must_match_error_product_and_channel'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});let decrypted;try{decrypted=decryptStoredError(error);const payload=decrypted.payload,exceptionClass=textValue(payload.exceptionClass||payload.exception),message=textValue(payload.message);if(!exceptionClass||!message)throw new Error('invalid_error_payload');const signature=errorSignature(exceptionClass,message);db.prepare(`INSERT INTO known_error_fix(signature,product_id,channel,release_id,note,created_by) VALUES(?,?,?,?,?,?) ON CONFLICT(signature,product_id,channel) DO UPDATE SET release_id=excluded.release_id,note=excluded.note,updated_at=CURRENT_TIMESTAMP`).run(signature,release.product_id,release.channel,release.id,textValue(req.body.note),req.user.id);res.json({updated:true,knownFix:knownFixFor(signature,error.product_code,error.channel,textValue(payload.version)||'-')});}catch(e){res.status(400).json({error:e.message});}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}});
app.delete('/api/v1/admin/errors/:id/known-fix',adminAuth,(req,res)=>{const error=db.prepare(`SELECT e.*,t.channel FROM application_error e LEFT JOIN terminal t ON t.id=e.terminal_id WHERE e.id=?`).get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});const product=db.prepare('SELECT * FROM product WHERE code=?').get(error.product_code);if(!product)return res.status(404).json({error:'product_not_found'});if(!canAccess(req.scopes,product.id,error.channel))return res.status(403).json({error:'scope_denied'});let decrypted;try{decrypted=decryptStoredError(error);const payload=decrypted.payload,exceptionClass=textValue(payload.exceptionClass||payload.exception),message=textValue(payload.message);if(!exceptionClass||!message)throw new Error('invalid_error_payload');db.prepare('DELETE FROM known_error_fix WHERE signature=? AND product_id=? AND channel=?').run(errorSignature(exceptionClass,message),product.id,error.channel);res.json({deleted:true});}catch(e){res.status(400).json({error:e.message});}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}});
app.get('/api/v1/admin/errors/:id/screenshot',adminAuth,(req,res)=>{const error=db.prepare('SELECT * FROM application_error WHERE id=?').get(req.params.id);if(!error)return res.status(404).json({error:'error_not_found'});const product=db.prepare('SELECT id FROM product WHERE code=?').get(error.product_code);if(!req.scopes.all&&(!product||!req.scopes.productIds.includes(product.id)))return res.status(403).json({error:'scope_denied'});let decrypted;try{decrypted=decryptStoredError(error);const screenshot=normalizeScreenshot(decrypted.payload.screenshotBase64);if(!screenshot)return res.status(404).json({error:'screenshot_not_stored'});const image=Buffer.from(screenshot.base64,'base64');res.type(screenshot.mime).set('Cache-Control','no-store, private').set('Content-Disposition','inline').end(image,()=>image.fill(0));}finally{if(decrypted){decrypted.plain.fill(0);decrypted.key.fill(0);}}});
app.get('/api/v1/admin/users',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});res.json(db.prepare(`SELECT u.id,u.username,u.name,u.role,u.active,u.created_at,group_concat(DISTINCT p.name) products,group_concat(DISTINCT uc.channel) channels FROM app_user u LEFT JOIN user_product up ON up.user_id=u.id LEFT JOIN product p ON p.id=up.product_id LEFT JOIN user_channel uc ON uc.user_id=u.id GROUP BY u.id ORDER BY u.name`).all());});
app.post('/api/v1/admin/users',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const role=req.body.role==='admin'?'admin':'operator',productIds=[...new Set((req.body.productIds||[]).map(Number))],channels=[...new Set(req.body.channels||[])];if(role==='operator'&&(!productIds.length||!channels.length))return res.status(400).json({error:'scope_required'});if(channels.some(c=>!CHANNELS.includes(c)))return res.status(400).json({error:'invalid_channel'});const id=db.transaction(()=>{const r=db.prepare('INSERT INTO app_user(username,name,password_hash,role) VALUES(?,?,?,?)').run(String(req.body.username||'').trim(),String(req.body.name||'').trim(),hashPassword(req.body.password),role);for(const productId of productIds)db.prepare('INSERT INTO user_product(user_id,product_id) VALUES(?,?)').run(r.lastInsertRowid,productId);for(const channel of channels)db.prepare('INSERT INTO user_channel(user_id,channel) VALUES(?,?)').run(r.lastInsertRowid,channel);return r.lastInsertRowid;})();res.status(201).json({id});});
app.patch('/api/v1/admin/users/:id',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});if(Number(req.params.id)===req.user.id&&req.body.active===false)return res.status(400).json({error:'cannot_disable_self'});db.prepare('UPDATE app_user SET active=? WHERE id=?').run(req.body.active?1:0,req.params.id);res.json({updated:true});});
app.post('/api/v1/admin/releases',adminAuth,upload.fields([{name:'artifact',maxCount:1},{name:'package',maxCount:1},{name:'rootFiles',maxCount:50}]),async(req,res,next)=>{
 const file=req.files?.artifact?.[0]||req.files?.package?.[0],artifactId=textValue(req.body.artifactId);let final,moved=false,createdReleaseId=null,ciArtifact=null;
 try{
  const artifactType=req.body.artifactType==='sql'?'sql':'package',expectedExtension=artifactType==='sql'?'.sql':'.zip',sqlContent=String(req.body.sqlContent||'').trim();
  if(artifactId){if(artifactType!=='package'||file)throw new Error('invalid_artifact_selection');ciArtifact=db.prepare('SELECT * FROM ci_artifact WHERE id=? AND user_id=? AND consumed_at IS NULL').get(artifactId,req.user.id);if(!ciArtifact)throw new Error('artifact_not_found');}
  if(artifactType==='package'&&(!artifactId&&!file||file&&path.extname(file.originalname).toLowerCase()!=='.zip'))throw new Error('zip_required');
  if(artifactType==='sql'&&!sqlContent&&(!file||path.extname(file.originalname).toLowerCase()!=='.sql'))throw new Error('sql_required');
  if(!['test','beta','production'].includes(req.body.channel))throw new Error('invalid_channel');
  const product=db.prepare('SELECT * FROM product WHERE id=?').get(req.body.productId);if(!product)throw new Error('product_not_found');
  if(!canAccess(req.scopes,product.id,req.body.channel))return res.status(403).json({error:'scope_denied'});
  const deadlineAt=normalizeFutureDeadline(req.body.deadlineAt);
  const ids=JSON.parse(req.body.targetClientIds||'[]');if(req.body.targetType!=='all'&&!ids.length)throw new Error('target_required');
  const folder=path.join(packagesPath,product.code);fs.mkdirSync(folder,{recursive:true});
  const version=String(req.body.version||'').trim(),safe=version.replace(/[^a-zA-Z0-9._-]/g,'');if(!safe)throw new Error('invalid_version');
  if(ciArtifact&&(ciArtifact.product_code!==product.code||ciArtifact.version!==version||ciArtifact.channel!==req.body.channel))throw new Error('artifact_metadata_mismatch');
  const name=`${safe}-${req.body.channel}${expectedExtension}`;final=path.join(folder,name);if(fs.existsSync(final))throw new Error('release_file_already_exists');
  let originalName,size,sha,manifest;
  if(artifactType==='sql'&&sqlContent){fs.writeFileSync(final,sqlContent+'\n','utf8');moved=true;originalName=name;size=fs.statSync(final).size;sha=await hashFile(final);}
  else if(artifactType==='sql'){fs.renameSync(file.path,final);moved=true;originalName=file.originalname;size=file.size;sha=await hashFile(final);}
  if(artifactType==='sql'){
   const run=db.transaction(()=>{const r=db.prepare('INSERT INTO release(product_id,version,channel,file_path,sha256,size_bytes,mandatory,minimum_version,notes,technical_notes,show_notes_pdv,artifact_type,original_name,deadline_at,published_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(product.id,version,req.body.channel,`${product.code}/${name}`,sha,size,req.body.mandatory==='true'?1:0,req.body.minimumVersion||null,req.body.notes||null,req.body.technicalNotes||null,req.body.showNotesPdv==='true'?1:0,artifactType,originalName,deadlineAt,req.user.id);if(req.body.targetType==='all')db.prepare("INSERT INTO release_target(release_id,target_type) VALUES(?,'all')").run(r.lastInsertRowid);else for(const id of ids)db.prepare("INSERT INTO release_target(release_id,target_type,client_id) VALUES(?,'client',?)").run(r.lastInsertRowid,id);db.prepare('INSERT INTO terminal_event(release_id,status,message,ip) VALUES(?,?,?,?)').run(r.lastInsertRowid,'published',`Versão ${version} publicada como script SQL, com prazo até ${deadlineAt}.`,req.ip);notifyReleasePublished(r.lastInsertRowid,product,req.body.channel,version);return r.lastInsertRowid;});
   return res.status(201).json({id:run(),sha256:sha,artifactType,fileName:originalName});
  }
  originalName=ciArtifact?.original_name||file.originalname;
  createdReleaseId=db.transaction(()=>{const r=db.prepare('INSERT INTO release(product_id,version,channel,file_path,sha256,size_bytes,mandatory,minimum_version,notes,technical_notes,show_notes_pdv,artifact_type,original_name,deadline_at,published_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(product.id,version,req.body.channel,`${product.code}/${name}`,'pending',0,req.body.mandatory==='true'?1:0,req.body.minimumVersion||null,req.body.notes||null,req.body.technicalNotes||null,req.body.showNotesPdv==='true'?1:0,artifactType,originalName,deadlineAt,req.user.id);if(req.body.targetType==='all')db.prepare("INSERT INTO release_target(release_id,target_type) VALUES(?,'all')").run(r.lastInsertRowid);else for(const id of ids)db.prepare("INSERT INTO release_target(release_id,target_type,client_id) VALUES(?,'client',?)").run(r.lastInsertRowid,id);return r.lastInsertRowid;})();
  const source=ciArtifact?path.resolve(packagesPath,ciArtifact.file_path):file.path;if(ciArtifact&&(!source.startsWith(incomingPath+path.sep)||!fs.existsSync(source)))throw new Error('artifact_file_not_found');
  const rootFiles=(req.files?.rootFiles||[]).map(item=>({originalname:item.originalname,data:fs.readFileSync(item.path)}));
  manifest=buildUpdatePackageFromZip(source,final,{product:product.code,channel:req.body.channel,version,releaseId:createdReleaseId,rootFiles});moved=true;size=fs.statSync(final).size;sha=await hashFile(final);
  db.transaction(()=>{db.prepare('UPDATE release SET sha256=?,size_bytes=? WHERE id=?').run(sha,size,createdReleaseId);db.prepare('INSERT INTO terminal_event(release_id,status,message,ip) VALUES(?,?,?,?)').run(createdReleaseId,'published',`Versão ${version} publicada como pacote de arquivos, com ${manifest.files.length} arquivo(s) e prazo até ${deadlineAt}.`,req.ip);if(ciArtifact)db.prepare('UPDATE ci_artifact SET consumed_at=CURRENT_TIMESTAMP WHERE id=?').run(ciArtifact.id);notifyReleasePublished(createdReleaseId,product,req.body.channel,version);})();
  if(ciArtifact&&fs.existsSync(source))fs.unlinkSync(source);
  res.status(201).json({id:createdReleaseId,sha256:sha,artifactType,fileName:name,manifest});
 }catch(e){if(file?.path&&fs.existsSync(file.path))fs.unlinkSync(file.path);if(moved&&final&&fs.existsSync(final))fs.unlinkSync(final);if(createdReleaseId)db.transaction(()=>{db.prepare('DELETE FROM release WHERE id=?').run(createdReleaseId);})();next(e);}
 finally{for(const item of req.files?.rootFiles||[])if(item.path&&fs.existsSync(item.path))fs.unlinkSync(item.path);}
});
app.patch('/api/v1/admin/releases/:id',adminAuth,(req,res)=>{const release=db.prepare('SELECT * FROM release WHERE id=?').get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const active=req.body.active===undefined?release.active:(req.body.active?1:0),blocked=req.body.blocked===undefined?release.blocked:(req.body.blocked?1:0);db.prepare('UPDATE release SET active=?,blocked=? WHERE id=?').run(active,blocked,release.id);res.json({updated:true,active:Boolean(active),blocked:Boolean(blocked)});});
app.delete('/api/v1/admin/releases/:id',adminAuth,(req,res)=>{const release=db.prepare(`SELECT r.*,p.code product_code FROM release r JOIN product p ON p.id=r.product_id WHERE r.id=?`).get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const installations=db.prepare('SELECT count(*) value FROM terminal WHERE product_code=? AND current_version=?').get(release.product_code,release.version).value;if(installations)return res.status(409).json({error:'release_installed',installations});db.transaction(()=>{db.prepare('UPDATE terminal_event SET release_id=NULL WHERE release_id=?').run(release.id);db.prepare('DELETE FROM release WHERE id=?').run(release.id);})();const shared=db.prepare('SELECT 1 FROM release WHERE file_path=? LIMIT 1').get(release.file_path),artifact=path.resolve(packagesPath,release.file_path);if(!shared&&artifact.startsWith(packagesPath+path.sep)&&fs.existsSync(artifact))fs.unlinkSync(artifact);res.json({deleted:true});});
app.get('/api/v1/admin/releases/:id/delete-impact',adminAuth,(req,res)=>{const release=db.prepare(`SELECT r.*,p.code product_code FROM release r JOIN product p ON p.id=r.product_id WHERE r.id=?`).get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const installations=db.prepare('SELECT count(*) value FROM terminal WHERE product_code=? AND current_version=?').get(release.product_code,release.version).value,events=db.prepare('SELECT count(*) value FROM terminal_event WHERE release_id=?').get(release.id).value,sharedArtifact=db.prepare('SELECT count(*) value FROM release WHERE file_path=? AND id<>?').get(release.file_path,release.id).value;res.json({canDelete:installations===0,installations,events,sharedArtifact:Boolean(sharedArtifact)});});
app.post('/api/v1/admin/releases/:id/copy',adminAuth,(req,res)=>{const source=db.prepare('SELECT * FROM release WHERE id=?').get(req.params.id);if(!source)return res.status(404).json({error:'release_not_found'});const channel=req.body.channel;if(!CHANNELS.includes(channel))return res.status(400).json({error:'invalid_channel'});if(!canAccess(req.scopes,source.product_id,source.channel)||!canAccess(req.scopes,source.product_id,channel))return res.status(403).json({error:'scope_denied'});const ids=(req.body.targetClientIds||[]).map(Number),targetType=req.body.targetType==='client'?'client':'all';if(targetType==='client'&&!ids.length)return res.status(400).json({error:'target_required'});const id=db.transaction(()=>{const r=db.prepare(`INSERT INTO release(product_id,version,channel,file_path,sha256,size_bytes,mandatory,minimum_version,notes,technical_notes,show_notes_pdv,artifact_type,original_name,deadline_at,published_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(source.product_id,req.body.version||source.version,channel,source.file_path,source.sha256,source.size_bytes,req.body.mandatory?1:0,req.body.minimumVersion||source.minimum_version,req.body.notes??source.notes,req.body.technicalNotes??source.technical_notes,req.body.showNotesPdv===undefined?source.show_notes_pdv:(req.body.showNotesPdv?1:0),source.artifact_type,source.original_name,normalizeFutureDeadline(req.body.deadlineAt),req.user.id);if(targetType==='all')db.prepare("INSERT INTO release_target(release_id,target_type) VALUES(?,'all')").run(r.lastInsertRowid);else for(const clientId of ids)db.prepare("INSERT INTO release_target(release_id,target_type,client_id) VALUES(?,'client',?)").run(r.lastInsertRowid,clientId);return r.lastInsertRowid;})();res.status(201).json({id});});
registerPortalRoutes(app,{db,adminAuth,installationAuth,storagePath});
app.use((e,_q,res,_n)=>{console.error(e);res.status(400).json({error:e.message||'internal_error'});});app.listen(port,()=>console.log(`Central de Atualização API: ${port}`));

