'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api} from '../../../lib/api';
import {Alert,AppBar,Box,Button,Chip,Container,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,FormControlLabel,IconButton,InputLabel,MenuItem,Paper,Select,Stack,Switch,Tab,Tabs,TextField,Toolbar,Tooltip,Typography} from '@mui/material';
import {ArrowBack as ArrowBackIcon,Delete as DeleteIcon,Download as DownloadIcon,Link as LinkIcon,UploadFile as UploadFileIcon} from '@mui/icons-material';

const fmt=v=>v?new Date(v.includes('T')?v:v.replace(' ','T')+'Z').toLocaleString('pt-BR'):'-';
const cat={incoming_invoice:'Nota entrada',outgoing_invoice:'Nota saida',system_backup:'Backup',other:'Outros'};
const status={pending:'Pendente',approved:'Aprovada',rejected:'Rejeitada',blocked:'Bloqueada',correction_requested:'Correcao'};

export default function DocumentsPage(){const router=useRouter(),[tab,setTab]=useState('files'),[data,setData]=useState({clients:[],files:[],offices:[],audit:[]}),[message,setMessage]=useState(''),[uploadOpen,setUploadOpen]=useState(false),[officeOpen,setOfficeOpen]=useState(false),[linking,setLinking]=useState(null);async function load(){try{const[clients,files,offices,audit]=await Promise.all([api('/admin/clients'),api('/admin/client-files'),api('/admin/accounting-offices'),api('/admin/portal-audit')]);setData({clients,files,offices,audit})}catch(e){setMessage(e.message)}}useEffect(()=>{if(!localStorage.getItem('token'))router.replace('/');else load()},[router]);const done=text=>{setMessage(text);setUploadOpen(false);setOfficeOpen(false);setLinking(null);load()};return <><AppBar position="sticky" color="inherit" elevation={0}><Toolbar><Tooltip title="Voltar"><IconButton onClick={()=>router.push('/dashboard/')}><ArrowBackIcon/></IconButton></Tooltip><Typography sx={{flex:1,fontWeight:700}}>Portal de documentos</Typography><Button startIcon={<UploadFileIcon/>} variant="contained" onClick={()=>setUploadOpen(true)}>Enviar arquivo</Button></Toolbar></AppBar><Container maxWidth="xl" sx={{py:4}}><Stack spacing={3}>{message&&<Alert onClose={()=>setMessage('')}>{message}</Alert>}<Paper><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab value="files" label="Arquivos"/><Tab value="offices" label="Contabilidades"/><Tab value="audit" label="Auditoria"/></Tabs><Box sx={{p:3}}>{tab==='files'&&<Files files={data.files} done={done}/>} {tab==='offices'&&<Offices offices={data.offices} clients={data.clients} create={()=>setOfficeOpen(true)} link={setLinking} done={done}/>} {tab==='audit'&&<Audit rows={data.audit}/>}</Box></Paper></Stack></Container><UploadDialog open={uploadOpen} close={()=>setUploadOpen(false)} clients={data.clients} done={done}/><OfficeDialog open={officeOpen} close={()=>setOfficeOpen(false)} done={done}/><LinkDialog value={linking} clients={data.clients} close={()=>setLinking(null)} done={done}/></>}

function Table({heads,rows}){return <Box sx={{overflowX:'auto'}}><Box sx={{minWidth:heads.length*150}}><Box sx={{display:'grid',gridTemplateColumns:`repeat(${heads.length},1fr)`,gap:2,p:1,fontWeight:700}}>{heads.map(h=><Typography key={h} variant="body2" fontWeight={700}>{h}</Typography>)}</Box>{rows.map((row,i)=><Box key={i} sx={{display:'grid',gridTemplateColumns:`repeat(${heads.length},1fr)`,gap:2,p:1.5,borderTop:'1px solid',borderColor:'divider',alignItems:'center'}}>{row.map((cell,j)=><Box key={j} sx={{minWidth:0,wordBreak:'break-word'}}>{cell}</Box>)}</Box>)}</Box></Box>}

function Files({files,done}){const[category,setCategory]=useState(''),filtered=useMemo(()=>files.filter(f=>!category||f.category===category),[files,category]);async function remove(file){try{await api(`/admin/client-files/${file.id}`,{method:'DELETE',body:JSON.stringify({reason:'Removido pelo painel'})});done('Arquivo removido')}catch(e){done(e.message)}}async function download(file){try{const response=await fetch(`/api/v1/admin/client-files/${file.id}/download`,{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}});if(!response.ok)throw new Error('Falha ao baixar arquivo');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.original_name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){done(e.message)}}return <Stack spacing={2}><FormControl size="small" sx={{maxWidth:260}}><InputLabel>Categoria</InputLabel><Select label="Categoria" value={category} onChange={e=>setCategory(e.target.value)}><MenuItem value="">Todas</MenuItem>{Object.entries(cat).map(([k,v])=><MenuItem key={k} value={k}>{v}</MenuItem>)}</Select></FormControl><Table heads={['Cliente','Categoria','Arquivo','Referencia','Tamanho','Visibilidade','Acoes']} rows={filtered.map(f=>[f.client_name,cat[f.category]||f.category,f.original_name,f.reference_date||'-',`${(f.size_bytes/1024/1024).toFixed(2)} MB`,<Chip key="v" size="small" label={f.public_enabled?'Publico':'Privado'} color={f.public_enabled?'info':'default'}/>,<Stack key="a" direction="row" spacing={.5}><Tooltip title="Baixar"><IconButton onClick={()=>download(f)}><DownloadIcon/></IconButton></Tooltip>{f.public_slug&&<Tooltip title="Copiar link publico"><IconButton onClick={()=>navigator.clipboard.writeText(`${location.origin}/api/v1/public/files/${f.public_slug}`)}><LinkIcon/></IconButton></Tooltip>}<Tooltip title="Excluir"><IconButton color="error" onClick={()=>remove(f)}><DeleteIcon/></IconButton></Tooltip></Stack>])}/></Stack>}

function Offices({offices,clients,create,link,done}){async function change(o,next){try{await api(`/admin/accounting-offices/${o.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});done('Contabilidade atualizada')}catch(e){done(e.message)}}return <Stack spacing={2}><Box><Button variant="contained" onClick={create}>Nova contabilidade</Button></Box><Table heads={['CNPJ','Nome','Contato','Situacao','Acoes']} rows={offices.map(o=>[o.cnpj,o.trade_name||o.legal_name,o.email||'-',<Chip key="s" size="small" label={status[o.status]||o.status} color={o.status==='approved'?'success':o.status==='blocked'?'error':'default'}/>,<Stack key="a" direction="row" spacing={1} flexWrap="wrap"><Button size="small" onClick={()=>change(o,'approved')}>Aprovar</Button><Button size="small" onClick={()=>change(o,'blocked')}>Bloquear</Button><Button size="small" onClick={()=>link(o)} disabled={!clients.length}>Vincular cliente</Button></Stack>])}/></Stack>}

function Audit({rows}){return <Table heads={['Data','Acao','Resultado','Identidade','Cliente','Arquivo']} rows={rows.map(r=>[fmt(r.created_at),r.action,r.result,r.identity_name||r.accounting_name||'-',r.client_name||'-',r.file_name||'-'])}/>}

function UploadDialog({open,close,clients,done}){const[form,setForm]=useState({clientId:'',category:'incoming_invoice',referenceDate:new Date().toISOString().slice(0,10),retentionDays:'60',visibility:'private',noteDirection:'entry',documentType:'nf',documentModel:'55',environment:'production',sequenceNumber:''}),[file,setFile]=useState(null),[error,setError]=useState('');const set=(k,v)=>setForm(x=>({...x,[k]:v}));async function send(){try{const body=new FormData();Object.entries(form).forEach(([k,v])=>body.append(k,v));body.append('file',file);await api('/admin/client-files',{method:'POST',body});done('Arquivo enviado')}catch(e){setError(e.message)}}return <Dialog open={open} onClose={close} fullWidth><DialogTitle>Enviar arquivo do cliente</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<FormControl><InputLabel>Cliente</InputLabel><Select label="Cliente" value={form.clientId} onChange={e=>set('clientId',e.target.value)}>{clients.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Categoria</InputLabel><Select label="Categoria" value={form.category} onChange={e=>set('category',e.target.value)}>{Object.entries(cat).map(([k,v])=><MenuItem key={k} value={k}>{v}</MenuItem>)}</Select></FormControl><TextField type="date" label="Referencia" InputLabelProps={{shrink:true}} value={form.referenceDate} onChange={e=>set('referenceDate',e.target.value)}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField label="Tipo" value={form.documentType} onChange={e=>set('documentType',e.target.value)}/><TextField label="Modelo" value={form.documentModel} onChange={e=>set('documentModel',e.target.value)}/><TextField label="Sequencial" value={form.sequenceNumber} onChange={e=>set('sequenceNumber',e.target.value)}/></Stack><TextField label="Retencao em dias" value={form.retentionDays} onChange={e=>set('retentionDays',e.target.value)}/><FormControlLabel control={<Switch checked={form.visibility==='public'} onChange={e=>set('visibility',e.target.checked?'public':'private')}/>} label="Gerar link publico encurtado"/><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancelar</Button><Button variant="contained" disabled={!form.clientId||!file} onClick={send}>Enviar</Button></DialogActions></Dialog>}

function OfficeDialog({open,close,done}){const[form,setForm]=useState({cnpj:'',legalName:'',tradeName:'',email:'',phone:'',responsibleName:'',status:'pending'}),[error,setError]=useState('');const set=(k,v)=>setForm(x=>({...x,[k]:v}));async function send(){try{await api('/admin/accounting-offices',{method:'POST',body:JSON.stringify(form)});done('Contabilidade cadastrada')}catch(e){setError(e.message)}}return <Dialog open={open} onClose={close} fullWidth><DialogTitle>Nova contabilidade</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="CNPJ" value={form.cnpj} onChange={e=>set('cnpj',e.target.value)}/><TextField label="Razao social" value={form.legalName} onChange={e=>set('legalName',e.target.value)}/><TextField label="Nome fantasia" value={form.tradeName} onChange={e=>set('tradeName',e.target.value)}/><TextField label="E-mail" value={form.email} onChange={e=>set('email',e.target.value)}/><TextField label="Telefone" value={form.phone} onChange={e=>set('phone',e.target.value)}/><TextField label="Responsavel" value={form.responsibleName} onChange={e=>set('responsibleName',e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancelar</Button><Button variant="contained" disabled={!form.cnpj||!form.legalName} onClick={send}>Cadastrar</Button></DialogActions></Dialog>}

function LinkDialog({value,clients,close,done}){const[form,setForm]=useState({clientId:'',canViewInvoices:true,canViewBackups:false,canViewOther:false,canUploadFiles:false});useEffect(()=>setForm({clientId:'',canViewInvoices:true,canViewBackups:false,canViewOther:false,canUploadFiles:false}),[value?.id]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));async function send(){try{await api(`/admin/accounting-offices/${value.id}/clients`,{method:'POST',body:JSON.stringify(form)});done('Cliente vinculado')}catch(e){done(e.message)}}return <Dialog open={!!value} onClose={close} fullWidth><DialogTitle>Vincular cliente</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Typography>{value?.trade_name||value?.legal_name}</Typography><FormControl><InputLabel>Cliente</InputLabel><Select label="Cliente" value={form.clientId} onChange={e=>set('clientId',e.target.value)}>{clients.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl><FormControlLabel control={<Switch checked={form.canViewInvoices} onChange={e=>set('canViewInvoices',e.target.checked)}/>} label="Notas fiscais"/><FormControlLabel control={<Switch checked={form.canViewBackups} onChange={e=>set('canViewBackups',e.target.checked)}/>} label="Backups"/><FormControlLabel control={<Switch checked={form.canViewOther} onChange={e=>set('canViewOther',e.target.checked)}/>} label="Outros documentos"/><FormControlLabel control={<Switch checked={form.canUploadFiles} onChange={e=>set('canUploadFiles',e.target.checked)}/>} label="Pode enviar arquivos"/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancelar</Button><Button variant="contained" disabled={!form.clientId} onClick={send}>Vincular</Button></DialogActions></Dialog>}
